### ISSUE TITLE
Assess medication in use CHW App: Record clients who are on medication

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-gates#2]
Quest_EN: Are you currently using any medication ? Answer: Yes/No

Quest_EN: Where did you buy the medicines? 
Answer: 
 1. Health Facility 
 2. ADDO Shop 
 3. Pharmacy

Quest_EN: List types of medication you are currently using (select all that apply)

Quest_EN: Did you pay for the medicine? 
Answer: 
Yes
No
Some

Quest_EN: What medicines did you get for free ? Answer:  select if yes: select from the list 

Quest_EN: Do you feel the price that you paid was affordable ?

Quest_EN: Among the medications you bought, which one was more expensive?

**Comment by gosso22** [comment]
Adolescent medicines list

[danger_signs_medication_adolescent.csv](https://github.com/d-tree-org/opensrp-client-chw-gates/files/13457286/danger_signs_medication_adolescent.csv)

**Comment by gosso22** [comment]
ANC and PNC Medication List

[danger_signs_medication_anc.csv](https://github.com/d-tree-org/opensrp-client-chw-gates/files/13457325/danger_signs_medication_anc.csv)

**Comment by gosso22** [comment]
Child Medication List

[danger_signs_medication_child.csv](https://github.com/d-tree-org/opensrp-client-chw-gates/files/13457373/danger_signs_medication_child.csv)
